### ISSUE TITLE
python feather package no longer needed?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-r#11]
Pandas can now read feather format, so it pandas version is recent enough, we do not need python feather package, right?

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_feather.html

**Comment by HenryLeongStat** [comment]
Looks good! Let me create a new branch for it!

**Comment by BoPeng** [comment]
Yes, I see no reason to switch then. Perhaps we can do that after two years after everyone is using pandas 0.20. :smile:
