### ISSUE TITLE
Proper function to show type and abbreviated version of variables.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-r#14]
https://github.com/vatlab/sos-notebook/issues/149

SoS now allows each language module to define a dedicated `preview` function to show the content of the variables. It used to simply print the variable but the output lacks type and size information, and can be very long that causes sos to freeze.

I am looking for some way to describe R variables and show some of its values. Currently I have found [the `describe` function in `Hmisc` package](https://www.rdocumentation.org/packages/Hmisc/versions/4.1-1/topics/describe), which more or less fits our need but it also seems to output too much for arrays of size 1.

```
> b = 'sdafdfdsa'
> describe(b)
b 
        n   missing  distinct     value 
        1         0         1 sdafdfdsa 
                    
Value      sdafdfdsa
Frequency          1
Proportion         1
> describe(seq(1, 20000))
seq(1, 20000) 
       n  missing distinct     Info     Mean      Gmd      .05      .10      .25 
   20000        0    20000        1    10000     6667     1001     2001     5001 
     .50      .75      .90      .95 
   10000    15000    18000    19000 

lowest :     1     2     3     4     5, highest: 19996 19997 19998 19999 20000
```

The biggest problem is also that it does not show the `type` and/or `class` (`array`, `data.frame` etc) and size of the variables (`len`, `dim` if appropriate).

Does anyone know anything better?

**Comment by BoPeng** [comment]
`print(var)` works reasonably well because it cuts off output of long variables.

**Comment by gaow** [comment]
@BoPeng I find `str` useful for this purpose:

```r
> b = 'asdfasdf'
> str(b)
 chr "asdfasdf"
> b = c(1,2,3)
> str(b)
 num [1:3] 1 2 3
> b = 1:2000
> str(b)
 int [1:2000] 1 2 3 4 5 6 7 8 9 10 ...
> b = list(a=runif(999), b=rnorm(888))
> str(b)
List of 2
 $ a: num [1:999] 0.171 0.625 0.136 0.669 0.517 ...
 $ b: num [1:888] 0.15 -0.38 0.597 -1.049 -1.463 ...
>
> b = matrix(0,5,5)
> str(b)
 num [1:5, 1:5] 0 0 0 0 0 0 0 0 0 0 ...
> b = data.frame(b)
> str(b)
'data.frame':	5 obs. of  5 variables:
 $ X1: num  0 0 0 0 0
 $ X2: num  0 0 0 0 0
 $ X3: num  0 0 0 0 0
 $ X4: num  0 0 0 0 0
 $ X5: num  0 0 0 0 0
> b = data.frame(matrix(0,500,500))
> str(b)
'data.frame':	500 obs. of  500 variables:
 $ X1  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ X2  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ X3  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ X4  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ X5  : num  0 0 0 0 0 0 0 0 0 0 ..
```

you see large data.frame is a bit of a problem. Maybe we should consult our friend @jdblischak on this one :)

**Comment by BoPeng** [comment]
OK. I have [used `str`](https://github.com/vatlab/sos-r/blob/master/src/sos_r/kernel.py#L300). It is not as pretty as the previous output for `data.frame` but at least it will not freeze sos. The side panel is currently not usable until https://github.com/vatlab/sos-notebook/issues/150 is implemented though.

**Comment by BoPeng** [comment]
The `preview` protocol is not fixed. Right now, it returns a tuple or list of

```
desc, preview
```
where `desc` is a `str` and will be displayed as `hint` (grayed), and `preview` can be a string that will be displayed as `stdout`, or ` dictionary with `{'text/html', ...}`, or even a tuple with the dictionary and related metadata. 

The interface is the same as the file preview protocol but the `desc` part is currently handled by `sos` so file previewers only need to return the second part.

So right now the `..sos.preview` function is identical to `str`, and we can do more if needed.

**Comment by BoPeng** [comment]
I think I am generally happy with the output of `str` for other data types, but `data.frame` could be bettered displayed with number of rows and columns followed by a table that lists, say, first and last few rows and columns of the data.

**Comment by HenryLeongStat** [comment]
I usually use `str()` + `head()` for understanding the data. 

If we are going to implement the `%preview` magic for R, we can add both the output of `str()` and `head()` for `%preview` magic?
