### ISSUE TITLE
Close R-help panel in the frontend

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-r#15]
When I type ?{r-functon()} in the side panel, a panel will show up in the bottom like:

<img width="1273" alt="screen shot 2018-12-11 at 12 18 38 pm" src="https://user-images.githubusercontent.com/26916551/49820980-f0875200-fd3e-11e8-8584-ac1d65239f0b.png">

However, I don't know how to close it except for minizing the panel size. Is there a better way to close it?

**Comment by BoPeng** [comment]
What is the behavior in regular r session?

**Comment by HenryLeongStat** [comment]
In Rstudio, it will show up in the side panel; in terminal, it is kinda like typing "less" in bash.

**Comment by HenryLeongStat** [comment]
Is it something to do with the IRkernel? Or we can edit it in sos-notebook's frontend?

**Comment by BoPeng** [comment]
This is opened by irkernel. I do not think we can do anything about it.
