### ISSUE TITLE
%get dataframe from SoS to R with index issues

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-r#21]
There is an issue getting dataframe from SoS to R when the dataframe index is not properly ordered (presumably). Here is what happens between SoS and R kernel:

![Screenshot from 2020-05-20 08-37-11](https://user-images.githubusercontent.com/917985/82446962-916e5680-9a75-11ea-83b6-9736c5da60da.png)

The test data and notebook are here:

[issue_reindex.tar.gz](https://github.com/vatlab/sos-notebook/files/4656855/issue_reindex.tar.gz)

**Comment by BoPeng** [comment]
Just to say your index is not even unique, it can be allowed but perhaps you have some upstream problem.

**Comment by BoPeng** [comment]
Running the transfer code directly shows that R does not allow duplicated rownames (see error message below).


![image](https://user-images.githubusercontent.com/9889312/82479357-e02ce800-9a97-11ea-895e-336d315b9222.png)

**Comment by BoPeng** [comment]
@gaow You can choose between

1. add a warning message and do not pass index
2. change data to have unique row index

**Comment by gaow** [comment]
The data frame was result of concatenation of various smaller ones. Now we reset index after the concatenation and the issue is fixed. 

An ideal default behavior is to retain index if it works, and drop it with a warning if it does not (option 1). At least a warning message would be quite helpful in this case.

**Comment by BoPeng** [comment]
Done.

![image](https://user-images.githubusercontent.com/9889312/82482395-6cd9a500-9a9c-11ea-8d9b-5e6f795c282b.png)

**Comment by BoPeng** [comment]
sos-r 0.19.3 is released.
