### ISSUE TITLE
Transfer R list to Python dictionary

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-r#3]
The default type match is `list` in R to `dict` in Python. I think we should use `OrderedDict` -- one of my procedures depends on the order of the list.

**Comment by BoPeng** [comment]
This is easy to do but I do not really like `OrderedDict` as it is quite verbose.

![image](https://user-images.githubusercontent.com/9889312/33465538-05adfebc-d60e-11e7-856f-9d28b7de6afa.png)

Let me know if this works for you.

**Comment by BoPeng** [comment]
I mean, I would rather see its `repr` as `{'A': 1, 'B': 2, 'C': 3}` as long as I know that the keys are ordered.

**Comment by BoPeng** [comment]
Let us say, because [dictionaries are ordered in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html), we can **create the dictionary in the order but still use **dict**?

**Comment by BoPeng** [comment]
Here is the idea:

![image](https://user-images.githubusercontent.com/9889312/33465810-8f43f32e-d60f-11e7-97ef-6bf17a84ee9d.png)

**Comment by gaow** [comment]
> dictionaries are ordered in Python 3.6, 

Oh sweet, although quite expected!! Great that'd do it. We should replace all OrderedDict in SoS codes.

**Comment by BoPeng** [comment]
It is already done. Note that previously we use

```
a = {'A': 1, 'B':2}
```
to transfer `list(A=1, B=2)` and the order is not guaranteed, and the new code uses
```
a= dict([('A': 1), ('B':2)])
```
which preserves order.
