### ISSUE TITLE
Support for numpy.nan

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-r#9]
Got the problem when I work on the `Ruby` test. `numpy.nan` isn't implemented for all the other languages.

<img width="572" alt="screen shot 2018-07-18 at 11 39 04 am" src="https://user-images.githubusercontent.com/26916551/42895340-37f83628-8a7f-11e8-8bed-e2cce00704b9.png">

**Comment by HenryLeongStat** [comment]
The Codacy test fails because of [line 45](https://github.com/vatlab/sos-r/commit/cc92d18bd2ffdb402a41f0789a536ecea41fc6bb#comments), but an error `UnboundLocalError: local variable 'numpy' referenced before assignment` shows up without [line 45](https://github.com/vatlab/sos-r/commit/cc92d18bd2ffdb402a41f0789a536ecea41fc6bb#comments). 

I think it is kinda weird because numpy is imported at the beginning...

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/51650746-fc298380-1f4e-11e9-98cc-9be3b4435514.png)

**Comment by BoPeng** [comment]
So in R `np.nan` should be `NaN`, not `NA`? R has `NA`, `NaN`, and `NULL`. I suppose

1. Python `None` should be R `NULL`
2. Python `np.nan` should be `NaN`
3. Not sure what to do with `NA`

**Comment by gaow** [comment]
I agree with 1 and 2. I do not think there is a straightforward `NA` in Python. `NA` means not available, `nan` means not a number. It is not clear what we should do about `NA` although pandas seems to use `nan` for `NA` in practice:

https://pandas.pydata.org/pandas-docs/stable/missing_data.html
